# Generated by Django 2.1.1 on 2018-10-01 13:40

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='inscription',
            field=markdownx.models.MarkdownxField(blank=True, help_text='The exact text of the inscription on this memorial.'),
        ),
    ]
