# Generated by Django 2.1.1 on 2018-09-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
