# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_monument'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='name',
            field=models.CharField(blank=True, help_text='If this memorial has a specific name, enter it here.', max_length=1024, null=True),
        ),
    ]
