# Generated by Django 2.1.1 on 2018-10-01 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181001_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
