# Generated by Django 2.1.1 on 2018-09-27 12:45

from django.db import migrations, models
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180927_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, exclude_digits=True, exclude_upper=True, exclude_vowels=True, length=4, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
