# Generated by Django 2.1.1 on 2019-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181001_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='cwgc',
            field=models.CharField(blank=True, help_text='If known, the entry number of this casualty with the Commonwealth War Graves Commission.', max_length=128),
        ),
        migrations.AddField(
            model_name='name',
            name='honorific',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
