# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monument_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_names', models.CharField(max_length=1024)),
                ('family_name', models.CharField(max_length=1024)),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_of_death', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='monument',
            name='inscription',
            field=models.TextField(blank=True, help_text='The exact text of the inscription on this monument.'),
        ),
        migrations.AlterField(
            model_name='monument',
            name='name',
            field=models.CharField(blank=True, default='', help_text='If this memorial has a specific name, enter it here.', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='monument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='core.Monument'),
        ),
    ]
