# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170321_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='date_of_death',
            field=models.DateField(null=True),
        ),
    ]
