# Generated by Django 2.1.1 on 2019-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190320_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='cwgc',
            field=models.CharField(blank=True, help_text='If known, the entry number of this casualty with the Commonwealth War Graves Commission.', max_length=128, verbose_name='CWGC Casualty'),
        ),
    ]
