# Generated by Django 2.1.1 on 2019-03-23 12:20

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190320_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
