# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170321_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='_inscription_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='monument',
            name='inscription',
            field=markitup.fields.MarkupField(blank=True, help_text='The exact text of the inscription on this monument.', no_rendered_field=True),
        ),
    ]
