# Generated by Django 2.1.1 on 2019-03-23 19:59

import autoslug.fields
from django.db import migrations
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190323_1220'),
    ]

    def migrate_forward(apps, schema_editor):
        Location = apps.get_model('core', 'Location')
        for location in Location.objects.all():
            location.slug = slugify(location.name)
            location.save()

    def reverse_func(apps, schema_editor):
        pass  # code for reverting migration, if any

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.RunPython(migrate_forward, reverse_func),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=False),
            preserve_default=False,
        ),
    ]
