# Generated by Django 2.1.1 on 2019-03-23 20:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
    ]
