# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170321_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='If this memorial has a specific name, enter it here.', max_length=1024)),
                ('inscription', markitup.fields.MarkupField(blank=True, help_text='The exact text of the inscription on this memorial.', no_rendered_field=True)),
                ('_inscription_rendered', models.TextField(blank=True, editable=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorials', to='core.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='monument',
            name='location',
        ),
        migrations.RemoveField(
            model_name='name',
            name='monument',
        ),
        migrations.DeleteModel(
            name='Monument',
        ),
        migrations.AddField(
            model_name='name',
            name='memorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='core.Memorial'),
            preserve_default=False,
        ),
    ]
