# Generated by Django 2.1.1 on 2019-03-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190323_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='pretty_name',
            field=models.CharField(default='REGENERATE PRETTY NAME', editable=False, max_length=1024),
            preserve_default=False,
        ),
    ]
