# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170321_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
