# Generated by Django 2.1.1 on 2019-03-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_memorial_pretty_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorial',
            options={'ordering': ['pretty_name']},
        ),
    ]
