# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_memorialimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialimage',
            name='image',
            field=models.ImageField(upload_to='memorials'),
        ),
    ]
