# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 17:18
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170323_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='memorials'),
        ),
    ]
