# Generated by Django 2.1.1 on 2019-03-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190326_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='tags',
            field=models.ManyToManyField(related_name='memorials', to='core.Tag'),
        ),
    ]
