# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_memorial_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=53.7972, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memorial',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=-1.4497, max_digits=9),
            preserve_default=False,
        ),
    ]
