# Generated by Django 2.1.1 on 2019-03-26 12:03

from django.db import migrations, models
import django.db.models.manager
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190326_1103'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='memorial',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='memorial',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Any additional information about this memorial (visible publicly).'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='notes',
            field=models.TextField(blank=True, help_text='Private notes about this memorial.'),
        ),
    ]
