# Generated by Django 2.1.1 on 2019-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190326_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='publish',
            field=models.BooleanField(default=False, help_text='Should this memorial be shown publicly?'),
            preserve_default=False,
        ),
    ]
