# Generated by Django 2.1.1 on 2019-03-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_memorial_publish'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='memorial',
            managers=[
            ],
        ),
    ]
