# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170707_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='_inscription_rendered',
        ),
        migrations.AlterField(
            model_name='memorial',
            name='inscription',
            field=models.TextField(blank=True, help_text='The exact text of the inscription on this memorial.'),
        ),
    ]
