# Generated by Django 2.1.1 on 2019-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190326_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='memorials', to='core.Tag'),
        ),
    ]
