# Generated by Django 2.1.1 on 2019-03-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190326_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorial',
            old_name='publish',
            new_name='published',
        ),
    ]
