# Generated by Django 2.1.1 on 2019-03-26 12:50

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190326_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, exclude_digits=True, exclude_upper=True, exclude_vowels=True, help_text='A randomly generated set of letters used to uniquely identify this memorial.', length=4, max_length=4, unique=True),
        ),
    ]
