# Generated by Django 2.1.1 on 2019-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190326_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='location_detail',
            field=models.CharField(blank=True, help_text="Additional information about this memorial's location, such as a plot number.", max_length=1024),
        ),
    ]
