# Generated by Django 2.1.1 on 2019-03-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_memorial_location_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='names_new',
            field=models.ManyToManyField(related_name='memorials', to='core.Name'),
        ),
    ]
