# Generated by Django 2.1.1 on 2019-03-31 20:19

from django.db import migrations


def migrate_names(apps, schema_editor):
    Memorial = apps.get_model('core', 'Memorial')

    for memorial in Memorial.objects.all():
        for name in memorial.names.all():
            memorial.names_new.add(name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_memorial_names_new'),
    ]

    operations = [
        migrations.RunPython(migrate_names),
    ]
