# Generated by Django 2.1.1 on 2019-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190331_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='slug',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
