# Generated by Django 2.1.1 on 2019-04-01 10:02

from django.db import migrations

import random


def generate_slugs(apps, schema_editor):
    Name = apps.get_model('core', 'Name')

    for name in Name.objects.all():
        name.slug = ''.join(random.choice(['b',
                                           'c',
                                           'd',
                                           'f',
                                           'g',
                                           'h',
                                           'j',
                                           'k',
                                           'l',
                                           'm',
                                           'n',
                                           'p',
                                           'q',
                                           'r',
                                           's',
                                           't',
                                           'v',
                                           'w',
                                           'x',
                                           'y',
                                           'z']) for x in range(6))
        # name.slug = '123'
        name.save()


def reverse_slugs(apps, schema_editor):
    Name = apps.get_model('core', 'Name')

    for name in Name.objects.all():
        name.slug = ''
        name.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_name_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, reverse_code=reverse_slugs),
    ]
