# Generated by Django 2.1.1 on 2019-04-01 10:12

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190401_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, exclude_digits=True, exclude_upper=True, exclude_vowels=True, help_text='A randomly generated set of letters used to uniquely identify this person.', length=6, max_length=6, unique=True),
        ),
    ]
