# Generated by Django 2.1.8 on 2019-04-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190401_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='cwgc',
        ),
        migrations.AddField(
            model_name='name',
            name='cwgc',
            field=models.CharField(blank=True, help_text='The Commonwealth War Graves Commission casualty number for this person.', max_length=128, verbose_name='CWGC Casualty'),
        ),
        migrations.AddField(
            model_name='name',
            name='service_number',
            field=models.CharField(blank=True, help_text="This person's service number.", max_length=128, verbose_name='Service Number'),
        ),
        migrations.AddField(
            model_name='name',
            name='wikidata',
            field=models.CharField(blank=True, help_text="This person's Wikidata ID.", max_length=128, verbose_name='Wikidata ID'),
        ),
    ]
