# Generated by Django 2.1.8 on 2019-04-01 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190401_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
