# Generated by Django 2.1.8 on 2019-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190401_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='outline',
            field=models.TextField(blank=True, help_text="A GeoJSON description of this location's outline."),
        ),
        migrations.AddField(
            model_name='memorial',
            name='outline',
            field=models.TextField(blank=True, help_text="A GeoJSON description of this memorial's outline."),
        ),
    ]
