# Generated by Django 2.2.10 on 2020-06-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20191105_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='plot_reference',
            field=models.CharField(blank=True, help_text="This memorial's plot reference, if known", max_length=16),
        ),
        migrations.AddField(
            model_name='name',
            name='import_key',
            field=models.UUIDField(editable=False, help_text='The UUID used to import this name record from the master import sheet, if present', null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='location_detail',
            field=models.CharField(blank=True, help_text="Additional information about this memorial's location, to help identify it if unclear or ambiguous.", max_length=1024),
        ),
    ]
