# Generated by Django 2.1.8 on 2019-10-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190414_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='longitude',
        ),
    ]
