# Generated by Django 2.1.8 on 2019-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20191008_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='died_aged',
            field=models.IntegerField(help_text='If known, the age of this person when they died.', null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='date_of_death',
            field=models.DateField(null=True),
        ),
    ]
