# Generated by Django 2.1.8 on 2019-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191105_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='died_aged',
            field=models.IntegerField(blank=True, help_text='If known, the age of this person when they died.', null=True),
        ),
    ]
