#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

script/update

echo "==> Running format checks…"
node_modules/.bin/prettier -c  --prose-wrap always ./**/*.md

echo "==> Running tests…"

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  python3 manage.py test "$1"
else
  python3 manage.py test
fi
