#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

script/update

if [ -n "$1" ]; then
  echo "==> Running requested tests…"
  ./manage.py test "$1"
else
  echo "==> Running formatting checks…"
  node_modules/.bin/prettier -c  --prose-wrap always ./**/*.md ./**/*.scss ./**/*.json
  echo "==> Running all tests…"
  coverage run --source='.' manage.py test
  coverage xml
fi