name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5

    - name: Install libsqlite3
      run: |
        sudo apt-get install libsqlite3-dev

    - uses: snok/install-poetry@v1.1.6

    - name: Run tests
      run: poetry run script/test
      env:
        DEBUG: True

        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}

        SECRET_KEY: ${{ secrets.SECRET_KEY }}
