name: Run tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.10

    - name: Install libsqlite3
      run: |
        sudo apt-get install libsqlite3-dev

    - uses: dschep/install-poetry-action@v1.3

    - name: Run tests
      run: poetry run script/test
      env:
        DEBUG: True

        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}

        SECRET_KEY: ${{ secrets.SECRET_KEY }}
